/* ZADACA 1 */

/* Prasanje 1. */
SELECT * FROM CONSULTANTS WHERE CONSULTANTNAME LIKE 'P%'

/* Prasanje 2. */
SELECT * FROM CONSULTANTS WHERE CONSULTANTNAME LIKE '%ska%' AND CONSULTANTNAME LIKE '% M%'

/* Prasanje 3. */
SELECT * FROM CONSULTANTS WHERE CONSULTANTNAME LIKE '% _____'

/* Prasanje 4. */
SELECT * FROM PRODUCTS WHERE PRODUCTNAME LIKE '% %'

/* Prasanje 5. */
SELECT * FROM PRODUCTS WHERE PRODUCTNAME LIKE '%d%' OR PRODUCTNAME LIKE '%D%'

/* Prasanje 6. */
SELECT P.PRODUCTNAME FROM PRODUCTS P
WHERE NOT EXISTS(SELECT P.PRODUCTID FROM PRODUCTS,ORDERDETAILS,ORDERS WHERE P.PRODUCTID = ORDERDETAILS.PRODUCTID AND ORDERDETAILS.ORDERID = ORDERS.ORDERID)

/* Prasanje 7. */
SELECT O.ORDERID,SUM(P.PRODUCTPRICE*OD.QUANTITY) AS VKUPNA_SUMA FROM ORDERS O,PRODUCTS P,ORDERDETAILS OD
WHERE P.PRODUCTID = OD.PRODUCTID AND OD.ORDERID = O.ORDERID 
GROUP BY O.ORDERID

/* Prasanje 8. */
SELECT O.PRODUCTID, COUNT(O.ORDERID)
FROM ORDERDETAILS O
GROUP BY O.PRODUCTID
HAVING COUNT(O.ORDERID) >= 2

/* Prasanje 9. */
SELECT C.CONSULTANTID,SUM(P.PRODUCTPRICE*OD.QUANTITY) AS VKUPEN_PROFIT
FROM CONSULTANTS C,ORDERDETAILS OD,ORDERS O,PRODUCTS P
WHERE C.CONSULTANTID =O.CONSULTANTID AND P.PRODUCTID = OD.PRODUCTID AND OD.ORDERID = O.ORDERID
GROUP BY C.CONSULTANTID

/* ZADACA 2 */

/* Prasanje 1. */
SELECT VRABOTENI.V AS SIFRA, VRABOTENI.IMEV AS VRABOTEN, PRETSTAVI.IMEP AS PRETSTAVA FROM ULOGI 
INNER JOIN BILETI ON ULOGI.P = BILETI.P AND ULOGI.IMA_ULOGA= 'glavna' AND BILETI.STATUS= 'redovna' AND BILETI.SCENA = 'golema' AND BILETI.PRODADENI > 0
INNER JOIN VRABOTENI ON ULOGI.V = VRABOTENI.V 
INNER JOIN PRETSTAVI ON ULOGI.P = PRETSTAVI.P

/* Prasanje 2. */
SELECT V, COUNT(*) FROM ULOGI GROUP BY V HAVING COUNT(*) = (SELECT MAX(C) FROM(SELECT COUNT (V) AS C FROM ULOGI GROUP BY V))

/* Prasanje 3. */
SELECT IMEV
FROM VRABOTENI
WHERE V = (SELECT V
FROM
  (SELECT V, ROUND(AVG(honorar), 2) avgHonorar
  FROM ZARABOTUVA
  GROUP BY V) avgHonorarTable,
  (SELECT MAX(avgHonorarTempTable.avgHonorar) maxAvgHonorar
  FROM
    (SELECT V, ROUND(AVG(honorar), 2) avgHonorar
    FROM ZARABOTUVA
    GROUP BY V) avgHonorarTempTable) maxAvgHonorarTable
WHERE avgHonorarTable.avgHonorar = maxAvgHonorarTable.maxAvgHonorar)

/* Prasanje 4. */
SELECT GRAD, COUNT(P)
FROM TEATRI TE
INNER JOIN BILETI BI on BI.T= BI.T
GROUP BY GRAD
ORDER BY GRAD ASC

/* Prasanje 5. */
SELECT * FROM
(SELECT P, SUM(HONORAR) sumHonorar
FROM ZARABOTUVA
GROUP BY P) honorarTabela,
(SELECT P, SUM(cena*prodadeni) sumProfit
FROM BILETI
GROUP BY P) profitTabela
WHERE profitTabela.P = honorarTabela.P AND sumProfit > sumHonorar

/* DOPOLNITELNA 1va */
SELECT P.PRODUCTNAME
FROM PRODUCTS P 
INNER JOIN CATEGORIES C ON P.CATEGORYID= C.CATEGORYID
WHERE C.CATEGORYNAME != 'Perfumes' AND P.PRODUCTPRICE >(
    SELECT MIN(P1.PRODUCTPRICE)
    FROM PRODUCTS P1
    INNER JOIN CATEGORIES C1 ON P1.CATEGORYID = C.CATEGORYID
    WHERE C1.CATEGORYNAME LIKE 'Perfumes'
)

/* DOPOLNITELNA 2ra */
SELECT TEATAR.IMET , SUM(BILET.CENA * BILET.PRODADENI)
FROM TEATRI TEATAR
INNER JOIN BILETI BILET on TEATAR.T = BILET.T
GROUP BY TEATAR.IMET 
HAVING SUM(BILET.cena * BILET.prodadeni) = (
    SELECT MAX(tableTemp.zarabotkaTemp)
    FROM(
    SELECT TEATAR.IMET, SUM(BILET.cena * BILET.prodadeni) zarabotkaTemp
    FROM TEATRI TEATAR
    INNER JOIN BILETI BILET ON TEATAR.T = BILET.T
    GROUP BY TEATAR.IMET) tableTemp
)